{{ if .Values.databases.zalando }}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    sso:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    sso: sso  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "12"
{{ end }}