{{ if .Values.databases.zalando }}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.zalandoPostgres.name }}
  namespace: {{ .Release.Namespace }}
spec:
  teamId: "sso"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    sso:  # database owner
    - superuser
    - createdb
  databases:
    sso: sso  # dbname: owner
  postgresql:
    version: "12"
{{ end }}