apiVersion: v1
kind: Secret
data:
  POSTGRES_DATABASE: {{ .Values.database.name | b64enc }}
{{- if .Values.databases.crunchydata }}
  POSTGRES_EXTERNAL_ADDRESS: {{ printf "%s.%s.svc.cluster.local" .Values.database.name (index .Values "crunchydata-postgres-operator" "pgo_operator_namespace") | b64enc }}
{{- end }}
{{- if .Values.databases.zalando }}
  POSTGRES_EXTERNAL_ADDRESS: {{ printf "%s.%s.svc.cluster.local" .Values.zalandoPostgres.name .Release.Namespace | b64enc }}
{{- end }}
  POSTGRES_EXTERNAL_PORT: {{ "5432" | b64enc }}
  POSTGRES_HOST: {{ .Values.database.name | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc }}
  POSTGRES_SUPERUSER: {{ "true" | b64enc }}
  POSTGRES_USERNAME: {{ .Values.database.username | b64enc }}
metadata:
  labels:
    app: keycloak
  name: keycloak-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque