{{ if .Values.databases.zalando }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s.%s" .Values.database.username .Values.zalandoPostgres.name }}.credentials.postgresql.acid.zalan.do
  namespace: {{ .Release.Namespace }}
  labels:
    application: spilo
    cluster-name: {{ .Values.zalandoPostgres.name }}
    team: sso
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  password: {{ .Values.database.password | b64enc }}
  username: {{ .Values.database.username | b64enc }}
type: Opaque
{{ end }}